name: Generate LwM2M object

on:
  push:
    branches:

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "16.x"

      - name: Install dependencies
        run: npm ci

      - name: Run unit tests
        run: npm test

      - name: Run end to end tests
        run: npx tsx src/e2e-tests/index.ts

      - name: Make sure project compiles
        run: npx tsc
